title: ZhanchongLin's Homepage
page-top-title: Zhanchong Lin
top-section-bg-text: Be what you wanna be
home-subtitle: Zhanchong Lin&ensp;|&ensp;林展冲
copyright-text: '&copy; 林展冲 2023-2025. All Rights Reserved.'
