title: zhanchonglin's Homepage
page-top-title: zhanchonglin
top-section-bg-text: Be what you wanna be
home-subtitle: zhanchonglin&ensp;|&ensp;林展冲
copyright-text: '&copy; 林展冲 2023-2025. All Rights Reserved.'
